Cleuteu/awesome_suits

- Gemfile
- Gemfile.lock
- app/uploaders/photo_uploader.rb
> setup cloudinary

- app/models/smoking.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20180820130535_create_smokings.rb
- db/schema.rb
- test/models/smoking_test.rb
@Cleuteu @e-ernoult @ynnsnr attention, ce message s'autodétruita dans 5 sec
> création modèle smoking et route associée

- app/models/suit.rb
- db/migrate/20180820141150_create_suits.rb
- db/schema.rb
- test/models/suit_test.rb
@ynnsnr @ThomPouillevet Plz check
> Suit model

- app/controllers/rentings_controller.rb
- app/controllers/suits_controller.rb
- app/models/renting.rb
- app/models/suit.rb
- app/models/user.rb
- db/migrate/20180820150533_create_rentings.rb
- test/controllers/rentings_controller_test.rb
- test/controllers/suits_controller_test.rb
- test/models/renting_test.rb
> created controllers and models

- app/controllers/suits_controller.rb
- app/views/suits/index.html.erb
- db/schema.rb
@ynnsnr @Cleuteu @e-ernoult veuillez merger. Thx
> suit index effectué. Validation appréciée

- app/controllers/suits_controller.rb
putain enfin @ThomPouillevet @Cleuteu @e-ernoult
> show added to suits_controller

- app/views/suits/show.html.erb
> show view added for suits

- config/routes.rb
> Added new and create in suits routes for tests

- app/models/suit.rb
- db/migrate/20180820161452_add_photo_to_suits.rb
- db/schema.rb
- db/seeds.rb
@ynnsnr @e-ernoult @ThomPouillevet
> add migration cloudary and add passwords for dev

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/suits/index.html.erb
@ynnsnr @Cleuteu @e-ernoult à merger plz
> Suit index view

- app/controllers/suits_controller.rb
- app/views/suits/new.html.erb
> Fixed new and create suit + show

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_card.scss
- app/views/suits/show.html.erb
- db/migrate/20180820161452_add_photo_to_suits.rb
@Cleuteu @ThomPouillevet @e-ernoult 
rien de changé, juste des commits apparus par magie après un pull master '-__-
> some fixes

- .gitignore
- app/views/suits/new.html.erb
- app/views/suits/show.html.erb
@e-ernoult @e-ernoult  il est maintenant possible d'ajouter une image lors de la création d'un costume et de la voir dans le show.
> add image when creating costume

- app/controllers/rentings_controller.rb
- app/views/suits/show.html.erb
- config/routes.rb
@ynnsnr @ThomPouillevet @e-ernoult 
Delete renting.
> Destroy rentings

- .gitignore
- app/assets/stylesheets/components/_card.scss
- app/views/suits/index.html.erb
flex box cards wip @e-ernoult @ThomPouillevet @Cleuteu
> Show price

- app/controllers/application_controller.rb
- app/views/suits/show.html.erb
- db/migrate/20180821103330_add_columns_to_users.rb
- db/schema.rb
- db/seeds.rb
> add names to users

- app/views/suits/_form_suit.html.erb
- app/views/suits/edit.html.erb
- app/views/suits/new.html.erb
> Added partial form for suits

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20180821121733_add_photo_to_users.rb
- db/schema.rb
> Add-photo-to-users

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/components/banner.js
- app/javascript/packs/application.js
- app/views/pages/home.html.erb
- package.json
- yarn.lock
Il y a encore du travail sur la navbar mais ça permet d'avoir la même déjà @e-ernoult @ynnsnr
> fix navbar and typed.js ne pas oublier bundle install

- app/javascript/packs/application.js
> cart delete

- app/assets/stylesheets/components/_card.scss
- app/javascript/components/card.js
- app/javascript/packs/application.js
- app/views/suits/index.html.erb
@Cleuteu @e-ernoult @ThomPouillevet
> card cart fixed

- app/javascript/components/banner.js
- app/javascript/packs/application.js
@ynnsnr @Cleuteu @e-ernoult j'ai corrigé la speed
> correction typed js speed

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/components/navbar.js
> fixed alerts

- app/models/suit.rb
- app/views/suits/_form_suit.html.erb
@ynnsnr @Cleuteu @e-ernoult 
Rajout de validation et de prix en EURO
> correction syntaxe du form

- app/views/suits/index.html.erb
photos if else placeholder @ThomPouillevet @Cleuteu @e-ernoult
> cards photo done

- app/assets/stylesheets/components/_card.scss
- app/views/suits/index.html.erb
cards link ok @ThomPouillevet @Cleuteu @e-ernoult
> cards link swag

- db/seeds.rb
> added photo to users in seeds

- app/views/shared/_navbar.html.erb
> deleted modal

- app/assets/stylesheets/components/_card.scss
- app/views/suits/index.html.erb
Cards plus tolérantes aux différences de formats d'image uploadées @ThomPouillevet @Cleuteu @e-ernoult
> avatar resized and misc

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_newsuit.scss
- app/javascript/components/navbar.js
- app/views/suits/_form_suit.html.erb
- app/views/suits/new.html.erb
> front de la view finalisé

- Gemfile
- Gemfile.lock
- app/controllers/suits_controller.rb
- app/javascript/components/autocomplete.js
- app/javascript/packs/map.js
- app/models/suit.rb
- app/views/layouts/application.html.erb
- app/views/suits/_form_suit.html.erb
- app/views/suits/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20180822082923_add_coordinates_to_suits.rb
- db/migrate/20180822083635_add_address_to_suits.rb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
@ThomPouillevet @ynnsnr @e-ernoult
> Google map

- app/controllers/rentings_controller.rb
- app/controllers/suits_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/policies/renting_policy.rb
- app/views/layouts/application.html.erb
- app/views/suits/_formrenting.html.erb
- app/views/suits/show.html.erb
- package.json
- test/policies/renting_policy_test.rb
- yarn.lock
> Added flatpickr

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/pages/_editsuit.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
> modification alert

- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/shared/_navbar.html.erb
- app/views/suits/show.html.erb
> modal removed

- app/models/suit.rb
- app/views/devise/registrations/new.html.erb
- db/migrate/20180822102639_add_phone_to_users.rb
- db/schema.rb
- db/seeds.rb
> added phones to users et feed the seed

- app/assets/stylesheets/components/_alert.scss
- app/views/suits/edit.html.erb
> front de la page edit suit

- app/views/suits/show.html.erb
> debbug show for suits

- app/controllers/suits_controller.rb
- app/views/suits/show.html.erb
@ynnsnr @ThomPouillevet @e-ernoult 
Map fixed pour les show
> bug with map fixed

- app/assets/stylesheets/pages/_newsuit.scss
- app/controllers/suits_controller.rb
- app/javascript/plugins/flatpickr.js
- app/views/suits/_formrenting.html.erb
> Date picker inline

- app/assets/stylesheets/pages/_newsuit.scss
- app/assets/stylesheets/pages/_show.scss
- app/views/suits/_formrenting.html.erb
- app/views/suits/new.html.erb
- app/views/suits/show.html.erb
> show design

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_loginpage.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
@ynnsnr @Cleuteu @e-ernoult Page Login, front effectué.
> front de la page login

- app/assets/stylesheets/layouts/_index.scss
- app/assets/stylesheets/layouts/_map.scss
- app/views/suits/index.html.erb
map added to index @ThomPouillevet @Cleuteu @e-ernoult
> map added to index

- db/seeds.rb
> changed seed with the names

- app/controllers/suits_controller.rb
- app/views/suits/owner_index.html.erb
> Changed owner index

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
> front create and edit user + ajout des links sur la navbar

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/layouts/_map.scss
- app/views/suits/index.html.erb
> index design finalized

- app/views/suits/index.html.erb
> fixed avatar in show

- app/views/shared/_navbar.html.erb
- app/views/suits/index.html.erb
- app/views/suits/owner_index.html.erb
> navbar my suits & my suits design

- app/views/suits/owner_index.html.erb
> add photo for random user

- app/controllers/suits_controller.rb
> redirection

- app/assets/stylesheets/pages/_newsuit.scss
- app/views/suits/_form_suit.html.erb
- app/views/suits/edit.html.erb
- app/views/suits/new.html.erb
- app/views/suits/owner_index.html.erb
> add a suit + button

- app/controllers/rentings_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/suits_controller.rb
- app/models/renting.rb
- app/models/review.rb
- app/models/suit.rb
- app/policies/review_policy.rb
- app/views/rentings/_formreview.html.erb
- app/views/rentings/index.html.erb
- app/views/rentings/new.html.erb
- app/views/rentings/show.html.erb
- app/views/suits/show.html.erb
- config/routes.rb
- db/migrate/20180823090711_create_reviews.rb
- db/migrate/20180823094358_add_title_to_review.rb
- db/schema.rb
- test/controllers/reviews_controller_test.rb
- test/models/review_test.rb
- test/policies/review_policy_test.rb
> Add reviews

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/layouts/_map.scss
- app/javascript/packs/map.js
- app/views/layouts/application.html.erb
- app/views/suits/index.html.erb
- app/views/suits/show.html.erb
> cards plus sobres et map fixed

- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
> flexbox de GQ

- app/controllers/messages_controller.rb
- app/controllers/rentings_controller.rb
- app/controllers/suits_controller.rb
- app/models/message.rb
- app/models/renting.rb
- app/models/user.rb
- app/policies/message_policy.rb
- app/views/rentings/_formmessage.html.erb
- app/views/rentings/show.html.erb
- config/routes.rb
- db/migrate/20180823123832_create_messages.rb
- db/schema.rb
- test/controllers/messages_controller_test.rb
- test/models/message_test.rb
- test/policies/message_policy_test.rb
> messages added to show renting

- app/assets/stylesheets/pages/_formreview.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_rentings_show.scss
- app/views/rentings/_formmessage.html.erb
- app/views/rentings/_formreview.html.erb
- app/views/rentings/index.html.erb
- app/views/rentings/show.html.erb
> architecture page review show

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_owner_index.scss
- app/views/suits/index.html.erb
- app/views/suits/new.html.erb
- app/views/suits/owner_index.html.erb
> design fix

- app/assets/stylesheets/components/_alert.scss
- app/views/rentings/_history_owner.html.erb
- app/views/rentings/_history_renter.html.erb
- app/views/rentings/index.html.erb
- app/views/suits/index.html.erb
- app/views/suits/new.html.erb
- app/views/suits/owner_index.html.erb
- app/views/suits/show.html.erb
> margins homogeneized

- db/migrate/20180823163752_add_pending_to_renting.rb
- db/schema.rb
> added pending to renting

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/pages/_editsuit.scss
- app/assets/stylesheets/pages/_newsuit.scss
- app/assets/stylesheets/pages/_owner_index.scss
- app/views/pages/home.html.erb
- app/views/rentings/index.html.erb
- app/views/suits/index.html.erb
- app/views/suits/owner_index.html.erb
- app/views/suits/show.html.erb
> bugs marign top fixed

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/suits/index.html.erb
@ynnsnr @ynnsnr @Cleuteu @e-ernoult
> search bar placées

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/layouts/_map.scss
- app/views/suits/owner_index.html.erb
> owner suits description

- app/controllers/rentings_controller.rb
- app/views/rentings/_history_owner.html.erb
> changed reservation route

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/layouts/_map.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_abbr.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_button.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_collection_label.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_custom_checkbox_switch.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_floating_labels.scss
- app/assets/stylesheets/simple_form-bootstrap/_form_multi_select.scss
- app/assets/stylesheets/simple_form-bootstrap/_simple_form-bootstrap.scss
- app/javascript/packs/map.js
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/rentings/_history_owner.html.erb
- app/views/rentings/_history_renter.html.erb
- app/views/shared/_footer.html.erb
- app/views/suits/_form_suit.html.erb
- app/views/suits/index.html.erb
- app/views/suits/show.html.erb
> search bar test

- app/controllers/suits_controller.rb
- app/javascript/packs/map.js
- app/views/suits/_map_box.html.erb
- app/views/suits/index.html.erb
- app/views/suits/owner_index.html.erb
> map markers on hover

- app/controllers/suits_controller.rb
- app/javascript/components/autocomplete.js
- app/views/pages/home.html.erb
> search by location

- app/assets/stylesheets/pages/_rentings_index.scss
- app/assets/stylesheets/pages/_rentings_show.scss
- app/controllers/messages_controller.rb
- app/controllers/rentings_controller.rb
- app/views/messages/_form.html.erb
- app/views/messages/_show.html.erb
- app/views/messages/create.js.erb
- app/views/rentings/_history_owner.html.erb
- app/views/rentings/show.html.erb
> v1 du chat

- app/assets/stylesheets/components/_filterform.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_suits_index.scss
- app/views/pages/home.html.erb
- app/views/suits/index.html.erb
> index filter width

- app/assets/stylesheets/pages/_rentings_show.scss
- app/views/messages/_show.html.erb
- app/views/rentings/_history_owner.html.erb
- app/views/rentings/show.html.erb
> changed messages front un peu
